name: Deploy Spektron API

on:
  push:
    branches:
      - main  # O deploy acontece toda vez que você der push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar comandos via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/spektron-system-ts
            git fetch origin main
            git reset --hard origin/main
            docker build --no-cache -t spektron-api .  # <--- ESSA LINHA É A CHAVE
            docker rm -f spektron-app || true
            docker run -d --name spektron-app -p 3000:3000 --env-file .env --restart always spektron-api